In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

### Data Understanding

In [2]:
df = pd.read_csv("E:/Capstone project/heart_2022_no_nans.csv")

In [3]:
df.shape

(246022, 40)

In [4]:
df.head()

State     Sex GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
0  Alabama  Female     Very good                 4.0               0.0   
1  Alabama    Male     Very good                 0.0               0.0   
2  Alabama    Male     Very good                 0.0               0.0   
3  Alabama  Female          Fair                 5.0               0.0   
4  Alabama  Female          Good                 3.0              15.0   

                                     LastCheckupTime PhysicalActivities  \
0  Within past year (anytime less than 12 months ...                Yes   
1  Within past year (anytime less than 12 months ...                Yes   
2  Within past year (anytime less than 12 months ...                 No   
3  Within past year (anytime less than 12 months ...                Yes   
4  Within past year (anytime less than 12 months ...                Yes   

   SleepHours            RemovedTeeth HadHeartAttack  ... HeightInMeters  \
0         9.0            None of them             No  ...           1.60   
1         6.0            None of them             No  ...           1.78   
2         8.0  6 or more, but not all             No  ...           1.85   
3         9.0            None of them             No  ...           1.70   
4         5.0                  1 to 5             No  ...           1.55   

  WeightInKilograms    BMI AlcoholDrinkers HIVTesting FluVaxLast12  \
0             71.67  27.99              No         No          Yes   
1             95.25  30.13              No         No          Yes   
2            108.86  31.66             Yes         No           No   
3             90.72  31.32              No         No          Yes   
4             79.38  33.07              No         No          Yes   

  PneumoVaxEver                                  TetanusLast10Tdap  \
0           Yes                                 Yes, received Tdap   
1           Yes  Yes, received tetanus shot but not sure what type   
2           Yes  No, did not receive any tetanus shot in the pa...   
3           Yes  No, did not receive any tetanus shot in the pa...   
4           Yes  No, did not receive any tetanus shot in the pa...   

  HighRiskLastYear CovidPos  
0               No       No  
1               No       No  
2               No      Yes  
3               No      Yes  
4               No       No  

[5 rows x 40 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   State                      246022 non-null  object 
 1   Sex                        246022 non-null  object 
 2   GeneralHealth              246022 non-null  object 
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object 
 6   PhysicalActivities         246022 non-null  object 
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object 
 9   HadHeartAttack             246022 non-null  object 
 10  HadAngina                  246022 non-null  object 
 11  HadStroke                  246022 non-null  object 
 12  HadAsthma                  246022 non-null  object 
 13  HadSkinCancer              24

In [6]:
df.describe()

PhysicalHealthDays  MentalHealthDays     SleepHours  HeightInMeters  \
count       246022.000000     246022.000000  246022.000000   246022.000000   
mean             4.119026          4.167140       7.021331        1.705150   
std              8.405844          8.102687       1.440681        0.106654   
min              0.000000          0.000000       1.000000        0.910000   
25%              0.000000          0.000000       6.000000        1.630000   
50%              0.000000          0.000000       7.000000        1.700000   
75%              3.000000          4.000000       8.000000        1.780000   
max             30.000000         30.000000      24.000000        2.410000   

       WeightInKilograms            BMI  
count      246022.000000  246022.000000  
mean           83.615179      28.668136  
std            21.323156       6.513973  
min            28.120000      12.020000  
25%            68.040000      24.270000  
50%            81.650000      27.460000  
75%            95.250000      31.890000  
max           292.570000      97.650000

In [7]:
for col in df.describe(include='object').columns:
    print('Column Name: ',col)
    print(df[col].unique())
    print('-'*50)

Column Name:  State
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico'
 'Virgin Islands']
--------------------------------------------------
Column Name:  Sex
['Female' 'Male']
--------------------------------------------------
Column Name:  GeneralHealth
['Very good' 'Fair' 'Good' 'Excellent' 'Poor']
--------------------------------------------------
Column Name:  LastCheckupTime
['Within past year (anytime less than 12 m

In [8]:
for col in df.describe(include='object').columns:
    print('Column Name: ',col)
    print(df[col].value_counts())
    print('-'*50)

Column Name:  State
Washington              15000
Maryland                 9165
Minnesota                9161
Ohio                     8995
New York                 8923
Texas                    7408
Florida                  7315
Kansas                   6145
Wisconsin                6126
Maine                    6013
Iowa                     5672
Hawaii                   5596
Virginia                 5565
Indiana                  5502
South Carolina           5471
Massachusetts            5465
Arizona                  5462
Utah                     5373
Michigan                 5370
Colorado                 5159
Nebraska                 5107
California               5096
Connecticut              5053
Georgia                  4978
Vermont                  4845
South Dakota             4405
Montana                  4264
Missouri                 4195
New Jersey               3967
New Hampshire            3756
Puerto Rico              3589
Idaho                    3468
Alaska              

### Data Cleaning

In [9]:
df.isnull().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI     

In [10]:
df.isna().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI     

In [11]:
# Dropping columns which we don't need.

df = df.drop(columns=['State','RemovedTeeth', 'LastCheckupTime', 'ChestScan', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap', 'HighRiskLastYear'])

In [12]:
df.columns

Index(['Sex', 'GeneralHealth', 'PhysicalHealthDays', 'MentalHealthDays',
       'PhysicalActivities', 'SleepHours', 'HadHeartAttack', 'HadAngina',
       'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'RaceEthnicityCategory', 'AgeCategory',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers',
       'CovidPos'],
      dtype='object')

In [13]:
df.describe(include='object')

Sex GeneralHealth PhysicalActivities HadHeartAttack HadAngina  \
count   246022        246022             246022         246022    246022   
unique       2             5                  2              2         2   
top     Female     Very good                Yes             No        No   
freq    127811         86999             191318         232587    231069   

       HadStroke HadAsthma HadSkinCancer HadCOPD HadDepressiveDisorder  ...  \
count     246022    246022        246022  246022                246022  ...   
unique         2         2             2       2                     2  ...   
top           No        No            No      No                    No  ...   
freq      235910    209493        225001  227028                195402  ...   

       DifficultyConcentrating DifficultyWalking DifficultyDressingBathing  \
count                   246022            246022                    246022   
unique                       2                 2                         2   
top                         No                No                        No   
freq                    219802            209952                    237682   

       DifficultyErrands  SmokerStatus  \
count             246022        246022   
unique                 2             4   
top                   No  Never smoked   
freq              229638        147737   

                                  ECigaretteUsage     RaceEthnicityCategory  \
count                                      246022                    246022   
unique                                          4                         5   
top     Never used e-cigarettes in my entire life  White only, Non-Hispanic   
freq                                       190128                    186336   

         AgeCategory AlcoholDrinkers CovidPos  
count         246022          246022   246022  
unique            13               2        3  
top     Age 65 to 69             Yes       No  
freq           28557          135307   167306  

[4 rows x 25 columns]

### Dropping duplicate rows 

In [14]:
df[df.duplicated()]

Sex GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
3765    Female     Very good                 0.0               0.0   
3802    Female     Very good                 0.0               0.0   
5702    Female     Excellent                 0.0               0.0   
8546    Female     Very good                 0.0               0.0   
14407     Male     Very good                 0.0               0.0   
...        ...           ...                 ...               ...   
245526  Female     Excellent                 0.0               0.0   
245696  Female     Very good                 0.0               0.0   
245699    Male     Very good                 0.0               0.0   
245871    Male     Very good                 0.0               0.0   
245962    Male     Excellent                 0.0               0.0   

       PhysicalActivities  SleepHours HadHeartAttack HadAngina HadStroke  \
3765                  Yes         8.0             No        No        No   
3802                  Yes         7.0             No        No        No   
5702                  Yes         7.0             No        No        No   
8546                   No         8.0             No        No        No   
14407                 Yes         7.0             No        No        No   
...                   ...         ...            ...       ...       ...   
245526                Yes         8.0             No        No        No   
245696                Yes         7.0             No        No        No   
245699                Yes         7.0             No        No        No   
245871                Yes         8.0             No        No        No   
245962                Yes         8.0             No        No        No   

       HadAsthma  ... DifficultyErrands   SmokerStatus  \
3765          No  ...                No   Never smoked   
3802          No  ...                No   Never smoked   
5702          No  ...                No   Never smoked   
8546          No  ...                No   Never smoked   
14407         No  ...                No   Never smoked   
...          ...  ...               ...            ...   
245526        No  ...                No   Never smoked   
245696        No  ...                No   Never smoked   
245699        No  ...                No  Former smoker   
245871        No  ...                No   Never smoked   
245962        No  ...                No   Never smoked   

                                  ECigaretteUsage     RaceEthnicityCategory  \
3765    Never used e-cigarettes in my entire life  White only, Non-Hispanic   
3802    Never used e-cigarettes in my entire life  White only, Non-Hispanic   
5702    Never used e-cigarettes in my entire life  White only, Non-Hispanic   
8546    Never used e-cigarettes in my entire life  White only, Non-Hispanic   
14407   Never used e-cigarettes in my entire life  White only, Non-Hispanic   
...                                           ...                       ...   
245526  Never used e-cigarettes in my entire life  White only, Non-Hispanic   
245696  Never used e-cigarettes in my entire life  Black only, Non-Hispanic   
245699  Never used e-cigarettes in my entire life  White only, Non-Hispanic   
245871  Never used e-cigarettes in my entire life  Black only, Non-Hispanic   
245962  Never used e-cigarettes in my entire life  White only, Non-Hispanic   

         AgeCategory HeightInMeters WeightInKilograms    BMI AlcoholDrinkers  \
3765    Age 40 to 44           1.68             63.50  22.60             Yes   
3802    Age 60 to 64           1.65             79.38  29.12              No   
5702    Age 75 to 79           1.63             56.70  21.46             Yes   
8546    Age 60 to 64           1.68             77.11  27.44             Yes   
14407   Age 30 to 34           1.88             77.11  21.83             Yes   
...              ...            ...               ...    ...             ...   
245526  Age 55 to 59           1.52             49.

In [15]:
df.drop_duplicates(inplace=True)

### Checking columns with numeric data and handling outliers.

In [16]:
# For numerical data
numerical_data = df.select_dtypes(include=[np.number])
numerical_columns = numerical_data.columns

In [17]:
# Outlier detection
from scipy import stats
z_scores = stats.zscore(numerical_data)
abs_z_scores = np.abs(z_scores)
outliers = (abs_z_scores > 3).all(axis=1)
print(f'Number of outliers in the data: {outliers.sum()}')

Number of outliers in the data: 0


### Normalization of variables for modeling 

In [18]:
dict_replace = {'No':0, 'Yes' : 1} 
df = df.replace(dict_replace)

dict_GeneralHealth = {'Excellent': 0, 'Very good' : 1, 'Good' : 2, 'Fair': 3, 'Poor': 4}
df['GeneralHealth'] = df['GeneralHealth'].replace(dict_GeneralHealth)

dict_HadDiabetes = {'No': 0, 'Yes' : 1, 'Yes, but only during pregnancy (female)' : 2, 
                    'No, pre-diabetes or borderline diabetes': 3}
df['HadDiabetes'] = df['HadDiabetes'].replace(dict_HadDiabetes)

dict_SmokerStatus = {'Never smoked': 0, 'Current smoker - now smokes some days' : 1, 
                     'Current smoker - now smokes every day' : 2, 'Former smoker': 3}
df['SmokerStatus'] = df['SmokerStatus'].replace(dict_SmokerStatus)


dict_CovidPos = {'No': 0, 'Yes' : 1, 'Tested positive using home test without a health professional' : 2}
df['CovidPos'] = df['CovidPos'].replace(dict_CovidPos)

dict_ECigaretteUsage = {'Never used e-cigarettes in my entire life': 0, 
                        'Use them every day' : 1, 'Use them some days' : 2, 'Not at all (right now)': 3}
df['ECigaretteUsage'] = df['ECigaretteUsage'].replace(dict_ECigaretteUsage)


In [19]:
df.BMI = df.BMI.apply(lambda x : 0 if x <= 24.9 else 1)
df.BMI.value_counts()

1    172526
0     72012
Name: BMI, dtype: int64

In [20]:
df['Sex'] = df['Sex'].apply(lambda x : 0 if x == 'Female' else 1)
df['Sex'].value_counts()

0    127150
1    117388
Name: Sex, dtype: int64

In [21]:
df['RaceEthnicityCategory'] = df['RaceEthnicityCategory'].apply(lambda x : 0 if x =='White only, Non-Hispanic'else 1)
df['RaceEthnicityCategory'].value_counts()

0    184880
1     59658
Name: RaceEthnicityCategory, dtype: int64

In [22]:
df['AgeCategory'] = df['AgeCategory'].replace(to_replace = df['AgeCategory'].unique(), value =  np.arange(0,13,1))

In [23]:
for column_content in df.columns:
    print(column_content)
    print(df[column_content].unique(),"\n")  

Sex
[0 1] 

GeneralHealth
[1 3 2 0 4] 

PhysicalHealthDays
[ 4.  0.  5.  3.  2. 25. 30. 15. 29.  8. 16. 20. 10.  9.  7.  1. 21.  6.
 27. 14. 12. 11. 13. 28. 17. 23. 24. 26. 18. 22. 19.] 

MentalHealthDays
[ 0. 15.  4. 25.  5. 30. 27.  3.  2.  1. 10. 20. 21.  6.  7.  8. 14.  9.
 12. 18. 29. 28. 17. 11. 16. 13. 26. 22. 24. 19. 23.] 

PhysicalActivities
[1 0] 

SleepHours
[ 9.  6.  8.  5.  7. 10.  4. 12.  3. 18. 11.  2.  1. 16. 14. 15. 13. 20.
 24. 23. 19. 17. 22.] 

HadHeartAttack
[0 1] 

HadAngina
[0 1] 

HadStroke
[0 1] 

HadAsthma
[0 1] 

HadSkinCancer
[0 1] 

HadCOPD
[0 1] 

HadDepressiveDisorder
[0 1] 

HadKidneyDisease
[0 1] 

HadArthritis
[1 0] 

HadDiabetes
[0 1 2 3] 

DeafOrHardOfHearing
[0 1] 

BlindOrVisionDifficulty
[0 1] 

DifficultyConcentrating
[0 1] 

DifficultyWalking
[0 1] 

DifficultyDressingBathing
[0 1] 

DifficultyErrands
[0 1] 

SmokerStatus
[3 0 2 1] 

ECigaretteUsage
[0 2 3 1] 

RaceEthnicityCategory
[0 1] 

AgeCategory
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 



In [24]:
df.head()

Sex  GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
0    0              1                 4.0               0.0   
1    1              1                 0.0               0.0   
2    1              1                 0.0               0.0   
3    0              3                 5.0               0.0   
4    0              2                 3.0              15.0   

   PhysicalActivities  SleepHours  HadHeartAttack  HadAngina  HadStroke  \
0                   1         9.0               0          0          0   
1                   1         6.0               0          0          0   
2                   0         8.0               0          0          0   
3                   1         9.0               0          0          0   
4                   1         5.0               0          0          0   

   HadAsthma  ...  DifficultyErrands  SmokerStatus  ECigaretteUsage  \
0          0  ...                  0             3                0   
1          0  ...                  0             3                0   
2          0  ...                  0             3                0   
3          0  ...                  0             0                0   
4          0  ...                  0             0                0   

   RaceEthnicityCategory  AgeCategory  HeightInMeters  WeightInKilograms  BMI  \
0                      0            0            1.60              71.67    1   
1                      0            1            1.78              95.25    1   
2                      0            2            1.85             108.86    1   
3                      0            3            1.70              90.72    1   
4                      0            3            1.55              79.38    1   

   AlcoholDrinkers  CovidPos  
0                0         0  
1                0         0  
2                1         1  
3                0         1  
4                0         0  

[5 rows x 31 columns]

### Model Building 

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
from sklearn import metrics

In [26]:
random_seed = 42

In [27]:
X= df.drop('HadHeartAttack', axis=1)

y= df['HadHeartAttack']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, train_size=0.7, random_state = 42)

In [28]:
df.shape

(244538, 31)

In [29]:
X_train.shape

(171176, 30)

In [30]:
X_test.shape

(73362, 30)

In [31]:
y_train.shape

(171176,)

In [32]:
y_test.shape

(73362,)

In [33]:
model = sm.Logit(y,X)
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.150505
         Iterations 8


In [34]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\Users\srhar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [37]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5
)

In [38]:
rf_model.fit(X=X_train, y=y_train)

RandomForestClassifier(max_depth=5, n_estimators=200)

In [39]:
rf_model.estimators_

[DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=158218673),
 DecisionTreeClassifier(max_depth=5, max_features='auto',
                        random_state=1001559618),
 DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=914596687),
 DecisionTreeClassifier(max_depth=5, max_features='auto',
                        random_state=2040425833),
 DecisionTreeClassifier(max_depth=5, max_features='auto',
                        random_state=1034804367),
 DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=369096922),
 DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=305581441),
 DecisionTreeClassifier(max_depth=5, max_features='auto',
                        random_state=1216453256),
 DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=305839487),
 DecisionTreeClassifier(max_depth=5, max_features='auto',
                        random_state=1832932816),
 DecisionTreeClassifier(max_depth=5, max_feat

In [40]:
rf_model.estimators_[0]

DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=158218673)

In [41]:
rf_model.estimators_[0].predict(X_test)[:10]

C:\Users\srhar\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
rf_model.feature_importances_

array([1.85929675e-02, 7.19008857e-02, 1.64720544e-02, 1.24072850e-03,
       2.27951254e-03, 2.11801806e-03, 6.08504707e-01, 8.35750952e-02,
       2.74247501e-04, 6.79313991e-04, 2.07632512e-02, 1.14316737e-04,
       9.53670568e-03, 1.07746053e-02, 2.73200553e-02, 5.41344939e-03,
       6.70319983e-04, 3.75441546e-04, 4.29926426e-02, 1.99525067e-03,
       2.99870817e-03, 8.21111036e-03, 4.43966815e-04, 3.45989537e-04,
       5.30609045e-02, 4.70267675e-03, 2.18775096e-03, 2.50898917e-04,
       1.96219853e-03, 2.42227016e-04])

### Model Evaluation 

In [43]:
y_pred = logreg.predict(X_test)

In [44]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.95


In [45]:
in_sample_preds = rf_model.predict(X_train)
out_sample_preds = rf_model.predict(X_test)

In [46]:
print('In-Sample Accuracy: %0.4f' % accuracy_score(y_train, in_sample_preds))
print('Out-of-Sample Accuracy: %0.4f' % accuracy_score(y_test, out_sample_preds))

In-Sample Accuracy: 0.9453
Out-of-Sample Accuracy: 0.9463


In [47]:
print('In-Sample Precision: %0.4f' % precision_score(y_train, in_sample_preds))
print('Out-of-Sample Precision: %0.4f' % precision_score(y_test, out_sample_preds))

In-Sample Precision: 0.8364
Out-of-Sample Precision: 0.7091


In [48]:
print('In-Sample Recall: %0.4f' % recall_score(y_train, in_sample_preds))
print('Out-of-Sample Recall: %0.4f' % recall_score(y_test, out_sample_preds))

In-Sample Recall: 0.0146
Out-of-Sample Recall: 0.0098
